latent_dim: 32
batch_size: 128
lr: 1.e-4
loss_weight: 1.
num_disc_updates: 8
gp_lambda: 50.
gpdata_lambda: 0.
cramer: False
js: True
stochastic_stepping: True

save_every: 300
num_epochs: 5101

feature_noise_power: NULL
feature_noise_decay: NULL

data_version: 'data_v4'
full_feature_space: True
include_pT_for_evaluation: True
pad_range: [-3, 5]
time_range: [-7, 9]
scaler: 'logarithmic'

architecture:
  generator:
    - block_type: 'fully_connected'
      arguments:
        units: [64, 64, 64, 128]
        activations: [
          'elu', 'elu', 'elu',
          " (
                    lambda x,
                           shift=0.01,
                           val=np.log10(2),
                           v0=np.log10(2) / 10: (
                        torch.where(
                            x > shift,
                            val + x - shift,
                            v0 + nn.ELU(
                                alpha=(v0 * shift / (val - v0))
                            )(x) * (val - v0) / shift
                        )
                    )
                )"
        ]
        kernel_init: 'glorot_uniform'
        input_shape: [37,]
        output_shape: [8, 16]

  discriminator:
    - block_type: 'connect'
      arguments:
        vector_shape: [5,]
        img_shape: [8, 16]
        vector_bypass: False
        concat_outputs: True
        block:
          block_type: 'conv'
          arguments:
            filters: [32, 64, 64, 64]
            kernel_sizes: [3, 3, 3, 2]
            paddings: ['same', 'same', 'valid', 'valid']
            activations: ['elu', 'elu', 'elu', 'elu']
            poolings: [[1, 2], 2, NULL, NULL]
            kernel_init: 'glorot_uniform'
            input_shape: 6
            output_shape: 64
            dropouts: [0.02, 0.02, 0.02, 0.02]
    - block_type: 'fully_connected'
      arguments:
        units: [128, 1]
        activations: ['elu', NULL]
        kernel_init: 'glorot_uniform'
        input_shape: [70,]
        output_shape: NULL
